version: 0.0
os: linux
files:
  - source: /b2c/build/libs/b2c.jar
    destination: /opt/impostor/b2c/
  - source: /b2b/build/libs/b2b.jar
    destination: /opt/impostor/b2b/
  - source: /admin/build/libs/admin.jar
    destination: /opt/impostor/admin/
hooks:
  AfterInstall:
    - location: /scripts/deploy.sh
      runas: root
      timeout: 600