services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: impostor
    ports:
      - "3307:3306"
  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6380:6379"
    restart: always
  localstack:
    container_name: localstack-container
    image: localstack/localstack
    ports:
      - "4566:4566"   #LocalStack 기본 포트
      - "4571:4571"   #S3 서비스용 포트
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh" # s3 Bucket 초기화 스크립트