services:
  mysql-db:
    image: mysql:8.0
    container_name: impostor
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - multi-module-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3
      timeout: 10s

  redis:
    image: redis:6
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - multi-module-network
    volumes:
      - redis_data:/data
    restart: always



  ###### admin ######
  admin:
    image: openjdk:11-jre-slim
    container_name: admin-container
    ports:
      - "8080:8080"
    volumes:
      - ./target/admin.jar:/app/admin.jar # 빌드된 JAR 파일을 컨테이너에 마운트
    command: [ "java", "-jar", "/app/admin.jar" ] # 외부에서 가져온 JAR 파일 실행
    networks:
      - multi-module-network
    depends_on:
      - mysql-db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306



  ###### b2b ######
  b2b:
    image: openjdk:11-jre-slim
    container_name: b2b-container
    ports:
      - "8081:8081"
    volumes:
      - ./target/admin.jar:/app/b2b.jar # 빌드된 JAR 파일을 컨테이너에 마운트
    command: [ "java", "-jar", "/app/b2b.jar" ] # 외부에서 가져온 JAR 파일 실행
    networks:
      - multi-module-network
    depends_on:
      - mysql-db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306



  ###### b2c ######
  b2c:
    image: openjdk:11-jre-slim
    container_name: b2c-container
    ports:
      - "8082:8082"
    volumes:
      - ./target/admin.jar:/app/b2c.jar # 빌드된 JAR 파일을 컨테이너에 마운트
    command: [ "java", "-jar", "/app/b2c.jar" ] # 외부에서 가져온 JAR 파일 실행
    networks:
      - multi-module-network
    depends_on:
      - mysql-db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306

volumes:
  mysql_data:
  redis_data:

networks:
  multi-module-network:
    driver: bridge