server:
  port: 8082


management:
  endpoint:
    beans:
      enabled: true  # 특정 엔드포인트 활성화
  endpoints:
    web:
      exposure:
        include: beans  # beans 엔드포인트를 공개

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/impostor
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  session:
    redis:
      flush-mode: on_save
  data:
    redis:
      host: 127.0.0.1
      port: 6380
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        orm:
          jdbc:
            bind: trace
cloud:
  aws:
    s3:
      endpoint: "http://localhost:4566"
      bucket: "local-bucket"
      region: "ap-northeast-2"
    credentials:
      secretKey: "secretKey"
      accessKey: "accessKey"
    stack:
      auto: false
