server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://impostor-mysql.cnc4e604qbk0.ap-northeast-2.rds.amazonaws.com:3306/impostor # rds 로 바뀌어야 함
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  session:
    redis:
      flush-mode: on_save
  data:
    redis:
      host: impostor-redis-cache-001.hgjofj.0001.apn2.cache.amazonaws.com
      password: ""
      port: 6379

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}
    credentials:
      secretKey: ${AWS_S3_SECRET_KEY}
      accessKey: ${AWS_S3_ACCESS_KEY}
    stack:
      auto: false
