server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 5MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  session:
    redis:
      flush-mode: on_save
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

cloud:
  aws:
    s3:
      endpoint: ""
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}
    credentials:
      secretKey: ${AWS_S3_SECRET_KEY}
      accessKey: ${AWS_S3_ACCESS_KEY}
    stack:
      auto: false
